"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
import dj_database_url
import pathlib

# ------------------------------------------------------------------
# 基本設定
# ------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-m)+n5cp=^9^8+k-*sfw_hpm=*u$*8=hp4b+4+sv8jss!wcuh3m"

DEBUG = True  # 本番では False にし、環境変数で上書きする

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ------------------------------------------------------------------
# アプリケーション定義
# ------------------------------------------------------------------
INSTALLED_APPS = [
    # --- Django 標準 ---
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # --- 追加 ---
    "rest_framework",
    "corsheaders",
    "user_accounts",        # カスタム User
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",        # ★最上位
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ------------------------------------------------------------------
# データベース
# ------------------------------------------------------------------
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{(pathlib.Path(__file__).resolve().parent.parent / 'db.sqlite3')}"
    )
}

# ------------------------------------------------------------------
# パスワードバリデータ
# ------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------------------------------------------
# 国際化
# ------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------
# 静的ファイル
# ------------------------------------------------------------------
STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------------------------
# 認証 & DRF
# ------------------------------------------------------------------
AUTH_USER_MODEL = "user_accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# ------------------------------------------------------------------
# CORS 設定
# ------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    *[o for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o],
]

# すべての *.vercel.app を許可したい場合は以下を有効にする
# CORS_ALLOWED_ORIGIN_REGEXES = [r"^https://.*\.vercel\.app$"]

CORS_ALLOW_CREDENTIALS = True 